---
title: "Regression"
author: "Aleksander Brynjulf Hübert"
date: "3/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(ggplot2)
library(glmnet)
library(ModelMetrics)
```

```{r}
adultData <- read.delim("data/adult.data", sep ="," ,header = FALSE, strip.white = TRUE)

colnames(adultData) <- c("age", "workclass", "fnlwgt", "eductation", "education_num", "marital", "occupation", "relationship", "race", "sex", "capital_gain", "capital_loss", "hours_per_week", "native_country", "income")

adultData[adultData == "?"] <- NA
adultData <- na.omit(adultData)
test_set_indices = sample(1:nrow(adultData),round(0.25*nrow(adultData)),replace = FALSE)
training_set = adultData[-test_set_indices,] 
test_set = adultData[test_set_indices,] 

```
Simple linear model
```{r}
linearmodel <- lm(data = training_set, income ~ . )

test_predictions <- predict(linearmodel, test_set)
test_mse  <- mse(test_set$income,test_predictions)
test_mse
```

#This code is weird because it creates approx 100 dummy vars to run the glmnet ridge regression. I don't know how to fix the issue yet.

```{r}
x_train <- training_set %>%
    select(-income)
y_train <- training_set %>%
    select(income)

x_test <- test_set %>%
    select(-income)
y_test <- test_set %>%
    select(income)

#converting to matrix fro the glmnet package
?model.matrix
x_train_mat <-  model.matrix(~. -1, x_train)
y_train_mat <- model.matrix(~. -1, y_train)[,1]

x_test_mat <- model.matrix(~. -1, x_test)
y_test_mat <-  model.matrix(~. -1, y_test)[,1]
```


```{r}
cv_ridge_model <- cv.glmnet(x_train_mat, y_train_mat, alpha = 0)
cv_ridge_model
ncol(x_train_mat)
cv_best_lambda <- cv_ridge_model$lambda.min
cv_best_lambda

cv_ridge_pred = predict(cv_ridge_model,s=cv_best_lambda ,x_test_mat)

cv_mse <-mse(cv_ridge_pred, y_test_mat)
cv_mse

test_mse - cv_mse
```

